export const ActionTypes = {
  ADD_USER: 'ADD_USER',
  GET_USER: 'GET_USER',
  CREATE_TEST: 'CREATE_TEST',
  EDIT_TEST: 'EDIT_TEST',
  REMOVE_TEST: 'REMOVE_TEST',
  CREATE_QUESTION: 'CREATE_QUESTION',
  EDIT_QUESTION: 'EDIT_QUESTION',
  REMOVE_QUESTION: 'REMOVE_QUESTION'
}
